### ISSUE TITLE
[Bug]: Cannot change item to make unbreakable.

### ISSUE THREAD

**Issue by Trogdayton** [ladylexxie/Perpetual-Durability#7]
### Minecraft Version

1.19.2

### Mod Verion

2.1.0

### What happened?

Used to be able to set the use item (default: netherstar) to anything. Newest version is missing that part of the config. Is this intentional?

**Comment by lexxieblack** [comment]
The new version is using tags instead of an item ID.
I'm fairly sure I wrote that in one of the changelogs, but it seems that CurseForge is having an epilepsy fit because it says none of my files have a changelog...
Anyway... It is something I still need to add to the wiki, long story short: you can use KubeJS or just normal datapacks to edit the items that get the `perpetual_durability:perpetual` tag.
You can find the default one [here](https://github.com/ladylexxie/Perpetual-Durability/blob/1.19.2/src/main/resources/data/perpetual_durability/tags/items/perpetual.json).

**Comment by Trogdayton** [comment]
Thanks!

**Comment by Trogdayton** [comment]
I'll see if I can figure the datapack thing out. Otherwise I'll use the previous build until I get it figured out.

**Comment by lexxieblack** [comment]
I've added a [new wiki page](https://github.com/ladylexxie/Perpetual-Durability/wiki/Changing-The-Catalyst) to show how to change the item :D

**Comment by Trogdayton** [comment]
Awesome, thanks!
